### ISSUE TITLE
Output of sensors cannot be parsed

### ISSUE THREAD

**Issue by onkobu** [jackbenny/check_temp#9]
Currently sensors' output looks like:

```
k10temp-pci-00c3
Adapter: PCI adapter
Tdie:         +27.0°C  (high = +70.0°C)
Tctl:         +27.0°C  
```

Adding -A removes the line starting with Adapter. But the combination of grep and head -n1 only yields k10temp-pci-00c3. Instead the second line seems to always contain the/a temperature. (Tdie could also be temp1 or any arbitrary string depending on the kernel. I'm running on kernel 5.4.72 with lm-sensors-3.6.0.)

**Comment by jackbenny** [comment]
Fixed by @onkobu
